CREATE TABLE kisiler (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ad_soyad VARCHAR(255) NOT NULL,
    tarih TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE malzemeler (
    id INT AUTO_INCREMENT PRIMARY KEY,
    kisi_id INT NOT NULL,
    malzeme_adi VARCHAR(255) NOT NULL,
    miktar INT DEFAULT 1,
    tarih TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (kisi_id) REFERENCES kisiler(id) ON DELETE CASCADE
);
